### ISSUE TITLE
AttributeError: 'module' object has no atttribute 'filechooserthumbview'

### ISSUE THREAD

**Issue by court-jus** [opqopq/BoardGameMaker#1]
Running

```
python main.py
```

on a debian sid with cython and python-kivy installed :

[traceback.txt](https://github.com/opqopq/BoardGameMaker/files/39995/traceback.txt)

**Comment by opqopq** [comment]
Did you already get the latest master  ? I got read of any ffilethumb dependencies.
If not, you can edit the file kv/editors.kv and:
1) remove the line at the beginning importintg FileThumbView
2) Look for FileChooserThumbView in the file (line 506) and remplace it with FileChooserListView

Thanks !

**Comment by court-jus** [comment]
OK je testerai ça :-)

**Comment by opqopq** [comment]
Fixed in 0.1 alpha release
